let mascotasPerroBD = [
    {
        nombre: "Chester",
        raza: "Golden retriever",
        edad: "12 meses",
        ubicacion: "Calle 54-12b 108 - Medellín Antioquia  Colombia",
        personalidad: ["Aventurero", "Paciente", "Tranquilo"],
        historia: "Chester es un perro muy valiente y leal, por lo general suele ser muy tranquilo, casi ni se siente en la casa, además es muy cariñoso y obediente . La razón por la cual nos tenemos que separar de él es porque nos vamos a ir a vivir al exterior y él desafortunadamente no nos puede acompañar, entonces estamos en busca de una persona que lo sepa cuidar con todo el corazón.",
        usuario: "Enrique Gómez",
        imgusuario: "https://i.ibb.co/0jk5rR8/Ellipse10.png",
        imagen: "https://i.ibb.co/nsxG80m/perro2.jpg",
        genero: "https://i.ibb.co/xFWqvbb/Component-5.png",
        id: 0,
        categoria: "perro"
    },
    {
        nombre: "Rocky",
        raza: "Rottweiler",
        edad: "3 meses",
        ubicacion: "4140 Parker Rd. Allentown, New Mexico 31134",
        personalidad: ["Cariñoso", "Juguetón", "Inquieto"],
        historia: "Rocky es un perrito muy lindo y cariñoso, tiene 5 hermanitos más y por cuestiones de espacio y tiempo no podremos cuidar a todos, nuestra misión es encontrar la familia ideal para él y seguro que tú eres la persona indicada.",
        usuario: "Maria Dolores",
        imgusuario: "https://i.ibb.co/JvbRKsn/Ellipse9.png",
        imagen: "https://i.ibb.co/WDfQyqB/perro1.jpg",
        genero: "https://i.ibb.co/xFWqvbb/Component-5.png",
        id: 1,
        categoria: "perro"
    },
    {
        nombre: "Papi",
        raza: "Chihuahua",
        edad: "5 meses",
        ubicacion: "Calle 32-120b 180 - Medellin Antioquia Colombia",
        personalidad: ["Cariñoso", "Juguetón", "Aventurero"],
        historia: "Papi es un perrito que llegó a nuestras vidas gracias a que lo encontramos en una casa abandonada, es un perro que es muy protector con sus dueños y que siempre está de buen humor. La razón por la que no lo puedo tener más es porque mi novio es alérgico a los perro asi que estamos buscando una familia que le de mucho amor.",
        usuario: "Sofia Álvarez",
        imgusuario: "https://i.ibb.co/JvbRKsn/Ellipse9.png",
        imagen: "https://i.ibb.co/tHgRQZh/perro3.jpg",
        genero: "https://i.ibb.co/xFWqvbb/Component-5.png",
        id: 2,
        categoria: "perro"
    },
    {
        nombre: "Pelusa",
        raza: "Bichón frisé",
        edad: "8 meses",
        ubicacion: "Calle 23-42a 113 - Medellín Antioquia Colombia",
        personalidad: ["Tranquilo", "Cariñoso", "Curioso"],
        historia: "Pelusa es una perrita que fue previamente entrenado en una academia canina así que suele ser muy obediente y tranquila, ella llego a mi vida ya que fue un regalo de un amigo pero lastimosamente dónde me voy a mudar no me permiten tener mascotas así que estoy buscando a una familia que la cuide y le de mucho amor.",
        usuario: "Martin Lemus.",
        imgusuario: "https://i.ibb.co/0jk5rR8/Ellipse10.png",
        imagen: "https://i.ibb.co/tpxYdr8/perro4.jpg",
        genero: "https://i.ibb.co/QbnsP1H/Property-1-female.png",
        id: 3,
        categoria: "perro"
    },
    {
        nombre: "Rufi",
        raza: "Pastor collie",
        edad: "2 meses",
        ubicacion: "Calle 12-160b 130 - Medellin Antioquia Colombia",
        personalidad: ["Cariñoso", "Tranquilo", "Paciente"],
        historia: "Rufi es una cachorro de una camada de 6 perritos que se encontraron en la calle con su madre en estado de desnutrición. Está un poco enfermito pero siempre está alegre y cariñoso, buscamos a la mejor familia que pueda darle los cuidados que necesita.",
        usuario: "Fernanda martinez",
        imgusuario: "https://i.ibb.co/JvbRKsn/Ellipse9.png",
        imagen: "https://i.ibb.co/G3nz2cQ/perro5.jpg",
        genero: "https://i.ibb.co/xFWqvbb/Component-5.png",
        id: 4,
        categoria: "perro"
    },
    {
        nombre: "Santo",
        raza: "Rottweiler",
        edad: "1 año",
        ubicacion: "Calle 62-420b 18 - Medellin Antioquia Colombia",
        personalidad: ["Aventurero", "Cariñoso", "Inquieto"],
        historia: "Santo fue rescatado de las peleas callejeras, traído a recuperación debido a sus múltiples heridas por otros perros y sus antiguos amos, ahora es un perro muy protector en buscar de un nuevo hogar lleno amor.",
        usuario: "Arturo Calle",
        imgusuario: "https://i.ibb.co/0jk5rR8/Ellipse10.png",
        imagen: "https://i.ibb.co/whV782K/perro6.jpg",
        genero: "https://i.ibb.co/xFWqvbb/Component-5.png",
        id: 5,
        categoria: "perro"
    },
    {
        nombre: "Carola",
        raza: "Husky",
        edad: "1 año",
        ubicacion: "Calle 22-320c 10 - Medellin Antioquia Colombia",
        personalidad: ["Perezoso", "Tranquilo", "Curioso"],
        historia: "Carola fue traída por sus antiguos dueños, ellos no la podian cudiar luego de que se volvió mamá, llegó con sus 3 cachorros y estamos buscando una familia que pueda adoptarlos a todos, no queremos separarlos.",
        usuario: "Luisa Pérez",
        imgusuario: "https://i.ibb.co/JvbRKsn/Ellipse9.png",
        imagen: "https://i.ibb.co/kmtzb9V/perro7.jpg",
        genero: "https://i.ibb.co/QbnsP1H/Property-1-female.png",
        id: 6,
        categoria: "perro"
    },
    {
        nombre: "Figo",
        raza: "Husky",
        edad: "1 año",
        ubicacion: "calle 32-132d 110 - Medellin Antioquia Colombia",
        personalidad: ["Aventurero", "Curioso", "Inquieto"],
        historia : "Es el papá de los cachorros de Carola, sus dueños lo maltrarón despues de preñar a Carola, así que un refugió lo rescató, a pesar de los maltratos Figo es muy curioso y en cada momento se mete en problemas pero nunca le faltan buenas aventuras.",
        usuario: "Luisa Pérez",
        imgusuario : "https://i.ibb.co/JvbRKsn/Ellipse9.png",
        imagen: "https://i.ibb.co/YbfyHkj/perro8.jpg",
        genero: "https://i.ibb.co/xFWqvbb/Component-5.png",
        id : 7,
        categoria: "perro"
    }
]

export default mascotasPerroBD